// <auto-generated />
using InsuranceAIPlatform.Services.AiAnalysis.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InsuranceAIPlatform.Services.AiAnalysis.Migrations
{
    [DbContext(typeof(AiAnalysisDbContext))]
    [Migration("20260527194402_InitialAiAnalysisPersistence")]
    partial class InitialAiAnalysisPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ai_analysis")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InsuranceAIPlatform.Services.AiAnalysis.Persistence.AiAnalysisRun", b =>
                {
                    b.Property<string>("RunId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ClaimId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ModelConfidence")
                        .HasColumnType("int");

                    b.Property<string>("ProviderMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Tokens")
                        .HasColumnType("int");

                    b.HasKey("RunId");

                    b.ToTable("AiAnalysisRuns", "ai_analysis");
                });

            modelBuilder.Entity("InsuranceAIPlatform.Services.AiAnalysis.Persistence.AiEvidenceReference", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Confidence")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("AiEvidenceReferences", "ai_analysis");
                });

            modelBuilder.Entity("InsuranceAIPlatform.Services.AiAnalysis.Persistence.AiFinding", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("AiFindings", "ai_analysis");
                });

            modelBuilder.Entity("InsuranceAIPlatform.Services.AiAnalysis.Persistence.AiRiskSignal", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("AiRiskSignals", "ai_analysis");
                });

            modelBuilder.Entity("InsuranceAIPlatform.Services.AiAnalysis.Persistence.AiEvidenceReference", b =>
                {
                    b.HasOne("InsuranceAIPlatform.Services.AiAnalysis.Persistence.AiAnalysisRun", "Run")
                        .WithMany("EvidenceReferences")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("InsuranceAIPlatform.Services.AiAnalysis.Persistence.AiFinding", b =>
                {
                    b.HasOne("InsuranceAIPlatform.Services.AiAnalysis.Persistence.AiAnalysisRun", "Run")
                        .WithMany("Findings")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("InsuranceAIPlatform.Services.AiAnalysis.Persistence.AiRiskSignal", b =>
                {
                    b.HasOne("InsuranceAIPlatform.Services.AiAnalysis.Persistence.AiAnalysisRun", "Run")
                        .WithMany("RiskSignals")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("InsuranceAIPlatform.Services.AiAnalysis.Persistence.AiAnalysisRun", b =>
                {
                    b.Navigation("EvidenceReferences");

                    b.Navigation("Findings");

                    b.Navigation("RiskSignals");
                });
#pragma warning restore 612, 618
        }
    }
}
