// <auto-generated />
using System;
using InsuranceAIPlatform.Services.AiAnalysis.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InsuranceAIPlatform.Services.AiAnalysis.Migrations
{
    [DbContext(typeof(AiAnalysisDbContext))]
    [Migration("20260604161120_AddRagFoundation")]
    partial class AddRagFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ai_analysis")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InsuranceAIPlatform.Services.AiAnalysis.Persistence.AiAnalysisRun", b =>
                {
                    b.Property<string>("RunId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ClaimId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuardrailFlagsJson")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("ModelConfidence")
                        .HasColumnType("int");

                    b.Property<string>("ModelName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PolicyExplanationText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProviderMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RecommendedActionJson")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("RiskLevel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SummaryText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Tokens")
                        .HasColumnType("int");

                    b.HasKey("RunId");

                    b.ToTable("AiAnalysisRuns", "ai_analysis");
                });

            modelBuilder.Entity("InsuranceAIPlatform.Services.AiAnalysis.Persistence.AiEvidenceReference", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Confidence")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("AiEvidenceReferences", "ai_analysis");
                });

            modelBuilder.Entity("InsuranceAIPlatform.Services.AiAnalysis.Persistence.AiFinding", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("AiFindings", "ai_analysis");
                });

            modelBuilder.Entity("InsuranceAIPlatform.Services.AiAnalysis.Persistence.AiRiskSignal", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("AiRiskSignals", "ai_analysis");
                });

            modelBuilder.Entity("InsuranceAIPlatform.Services.AiAnalysis.Rag.Persistence.EvidenceChunk", b =>
                {
                    b.Property<string>("ChunkId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ChunkHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ClaimId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("EmbeddingDim")
                        .HasColumnType("int");

                    b.Property<string>("EmbeddingJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmbeddingModel")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<string>("SourceVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TokenCount")
                        .HasColumnType("int");

                    b.HasKey("ChunkId");

                    b.HasIndex("ClaimId");

                    b.ToTable("EvidenceChunks", "ai_analysis");
                });

            modelBuilder.Entity("InsuranceAIPlatform.Services.AiAnalysis.Rag.Persistence.PolicyClause", b =>
                {
                    b.Property<string>("ClauseId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ClauseType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<string>("PolicyId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ClauseId");

                    b.HasIndex("ProductCode");

                    b.ToTable("PolicyClauses", "ai_analysis");
                });

            modelBuilder.Entity("InsuranceAIPlatform.Services.AiAnalysis.Rag.Persistence.RagAuditTrace", b =>
                {
                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("AdvisoryOnly")
                        .HasColumnType("bit");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CitationsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("CompletionTokens")
                        .HasColumnType("int");

                    b.Property<int>("Confidence")
                        .HasColumnType("int");

                    b.Property<long>("CostMicros")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("int");

                    b.Property<string>("ProviderMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("QueryText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RetrievalMs")
                        .HasColumnType("bigint");

                    b.Property<string>("RetrievedChunkIdsCsv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UseCase")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("TraceId");

                    b.HasIndex("ClaimId");

                    b.ToTable("RagAuditTraces", "ai_analysis");
                });

            modelBuilder.Entity("InsuranceAIPlatform.Services.AiAnalysis.Rag.Persistence.RagEvaluationQuestion", b =>
                {
                    b.Property<string>("QuestionId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ClaimId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ExpectedAnswerKeywordsCsv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpectedSourceChunkIdsCsv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("MustNotCiteChunkIdsCsv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UseCase")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("QuestionId");

                    b.HasIndex("ClaimId");

                    b.ToTable("RagEvaluationQuestions", "ai_analysis");
                });

            modelBuilder.Entity("InsuranceAIPlatform.Services.AiAnalysis.Persistence.AiEvidenceReference", b =>
                {
                    b.HasOne("InsuranceAIPlatform.Services.AiAnalysis.Persistence.AiAnalysisRun", "Run")
                        .WithMany("EvidenceReferences")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("InsuranceAIPlatform.Services.AiAnalysis.Persistence.AiFinding", b =>
                {
                    b.HasOne("InsuranceAIPlatform.Services.AiAnalysis.Persistence.AiAnalysisRun", "Run")
                        .WithMany("Findings")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("InsuranceAIPlatform.Services.AiAnalysis.Persistence.AiRiskSignal", b =>
                {
                    b.HasOne("InsuranceAIPlatform.Services.AiAnalysis.Persistence.AiAnalysisRun", "Run")
                        .WithMany("RiskSignals")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("InsuranceAIPlatform.Services.AiAnalysis.Persistence.AiAnalysisRun", b =>
                {
                    b.Navigation("EvidenceReferences");

                    b.Navigation("Findings");

                    b.Navigation("RiskSignals");
                });
#pragma warning restore 612, 618
        }
    }
}
