// <auto-generated>
//     Generated from RagSeeder.cs by the Lease 5 corpus generator.
//     Canonical ENGLISH RAG corpus keyed by stable id. The backfill uses this to
//     bring already-seeded rows up to the current corpus without deleting anything.
//     Regenerate whenever RagSeeder's corpus changes.
// </auto-generated>
namespace InsuranceAIPlatform.DbMigrator;

/// <summary>Canonical English RAG corpus, keyed by stable identifier.</summary>
public static class EnglishOnlyBackfillCorpus
{
    /// <summary>ChunkId -> canonical English evidence text.</summary>
    public static readonly IReadOnlyDictionary<string, string> ChunkText =
        new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["CLM-1006-application#0"] = "Customer statement: a road traffic accident occurred on 18.05.2026 in Springfield. The Toyota Camry 2021 sustained damage to the front bumper and wing.",
        ["CLM-1006-police#0"] = "Police report No. PR-2026/05/441: a collision between two vehicles on 18.05.2026 is confirmed. The other driver was found at fault and an administrative report was filed.",
        ["CLM-1006-police#1"] = "Weather conditions at the time of the accident: rain, wet road surface. There were no injuries. Both vehicles remained at the scene until the patrol arrived.",
        ["CLM-1006-invoice#0"] = "Repair invoice: front bumper replacement 980 dollars, painting 740 dollars, bodywork 1000 dollars. Total repair amount 2720 US dollars.",
        ["CLM-1006-invoice#1"] = "The repair estimate of 2720 dollars exceeds the average benchmark of 1970 dollars by 38 percent. The discrepancy requires review by a human adjuster.",
        ["CLM-1006-policy-terms#0"] = "Policy Auto Comprehensive POL-2025-AC-4421 covers losses from a road traffic accident. A deductible of 500 dollars applies to the insured event.",
        ["CLM-1006-statement#0"] = "Driver statement: the car ahead braked sharply and, because of the wet surface, the collision could not be avoided. Speed was within the limit.",
        ["CLM-1006-photo-front#0"] = "Photo of the front bumper: visible cracks and deformation, consistent with the description of the accident. Recognition confidence 92 percent.",
        ["CLM-1006-photo-rear#0"] = "The rear bumper photo is missing. The document package is incomplete: 6 of 7 required items provided. The rear bumper photo must be requested.",
        ["CLM-1006-repair-detail#0"] = "Repair breakdown: the front bumper of the Toyota Camry 2021 was replaced (original part, article 521190X910). The catalogue labour time for bodywork is 8 hours; 14 hours were billed.",
        ["CLM-1006-repair-detail#1"] = "Comparative assessment: average workshop rates in the Springfield area are 85-95 dollars per labour hour. The billed rate is 120 dollars. The rate excess requires human review.",
        ["CLM-1006-coverage-check#0"] = "Exclusion check: the driver was sober at the time of the accident, no racing took place, and the road was a public road. No exclusion under policy POL-2025-AC-4421 was found. The insured event is covered.",
        ["CLM-1006-approval-summary#0"] = "Preliminary conclusion: the insured event falls under Auto Comprehensive coverage. The amount payable after the 500 dollar deductible is to be confirmed once the adjuster reviews the invoice. Documents 6/7 — request the rear bumper photo.",
        ["CLM-1007-application#0"] = "Customer statement: a side collision on 26.05.2026 in Riverside. The Skoda Octavia sustained damage to the left door and mirror.",
        ["CLM-1007-photo-front#0"] = "Photo of the Skoda Octavia front wing: scratches and a minor dent. Recognition confidence 75 percent.",
        ["CLM-1007-invoice#0"] = "The repair invoice is missing. Without the invoice the repair amount cannot be assessed. The document must be requested from the customer.",
        ["CLM-1007-police#0"] = "Police report RIVERSIDE-2026/05/887: the collision is confirmed and an accident diagram was drawn. There were no injuries and the second driver admitted fault.",
        ["CLM-1007-statement#0"] = "Driver statement: the other vehicle failed to give way while changing lanes and struck the left wing of the Skoda Octavia. The policyholder braked but could not avoid the impact.",
        ["CLM-1007-missing-docs#0"] = "Missing document list: repair invoice (required), photo of the right side of the vehicle (recommended). Without the invoice the indemnity amount cannot be determined. A request was sent to the customer.",
        ["CLM-1008-application#0"] = "Customer statement: road accident on 26.05.2026 in Riverside. The document package is complete.",
        ["CLM-1008-police#0"] = "Police report RIVERSIDE-12345: the collision is confirmed and was filed under the simplified accident procedure.",
        ["CLM-1008-invoice#0"] = "Repair invoice: the repair amount is within the average benchmark and no deviation was found.",
        ["CLM-1008-coverage-check#0"] = "Coverage check: the insured event falls under the Auto Comprehensive policy. No exclusion was established. The documents are complete and the repair amount is normal.",
        ["CLM-1008-photo#0"] = "The photographs confirm the damage: the rear bumper photo shows body deformation consistent with the collision mechanism. Confidence 88 percent.",
        ["CLM-1008-approval-summary#0"] = "Recommendation: the claim is fully documented and no anomalies were found. The payout may proceed after the standard signature check. Low risk.",
        ["CLM-1009-application#0"] = "Customer statement: road accident on 02.06.2026 in Madison. The Honda Accord sustained damage to the right side of the body. The policyholder requests reimbursement of the repair.",
        ["CLM-1009-police#0"] = "Police report MADISON-2026/06/102: an administrative offence report was filed. The Honda Accord driver was sent for a medical examination and alcohol intoxication of 1.2 promille was established.",
        ["CLM-1009-police#1"] = "Medical report No. MD-2026/0612: alcohol intoxication of the policyholder at the time of the accident was established. The document is attached to the claim file.",
        ["CLM-1009-exclusion-check#0"] = "Exclusion check: exclusion CLA-AC-EXCL-001 — losses caused while driving under alcohol intoxication are not covered. The medical report confirms the policyholder was intoxicated. The insured event is excluded from coverage.",
        ["CLM-1009-denial-summary#0"] = "Preliminary conclusion: denial of the payout. Basis — clause CLA-AC-EXCL-001 of the Auto Comprehensive policy: alcohol intoxication is documented. Send the customer an official denial notice citing the exclusion clause.",
        ["CLM-1009-invoice#0"] = "Repair invoice MADISON: repair of the right side of the Honda Accord — door replacement 1200 dollars, bodywork 600 dollars, painting 400 dollars. Total amount 2200 dollars. The invoice is filed with the claim, however no payout is made because of the exclusion.",
        ["CLM-1009-coverage-final#0"] = "Coverage check summary for CLM-1009: the insured event is not covered. The intoxication exclusion applies based on the police report and the medical report. The payout is denied.",
        ["CLM-1010-application#0"] = "Customer statement: a road traffic accident on 28.05.2026 in Greenville. Volkswagen Passat 2020, a collision at an intersection, with damage to the front bumper and bonnet.",
        ["CLM-1010-police#0"] = "Police report GREENVILLE-2026/05/339: a collision of vehicles at an intersection on 28.05.2026 is confirmed. Violation of intersection right-of-way rules. An administrative report was filed.",
        ["CLM-1010-invoice#0"] = "Repair invoice Greenville: front bumper replacement for the Volkswagen Passat 1800 dollars, bonnet repair 2100 dollars, paint work 1400 dollars. Total repair amount 5300 US dollars.",
        ["CLM-1010-invoice#1"] = "The repair estimate of 5300 dollars exceeds the average benchmark for the Volkswagen Passat (2800 dollars) by 89 percent. This significant benchmark excess requires review by a human adjuster.",
        ["CLM-1010-photo-front#0"] = "Photo of the Volkswagen Passat front bumper: visible scratches and slight deformation. The extent of damage is consistent with a low-speed collision.",
        ["CLM-1010-photo-mismatch#0"] = "Mismatch between the photo and the invoice: the invoice bills for bumper replacement and bonnet repair, yet the photo shows only bumper scratches with no bonnet damage. This mismatch between documents requires human review.",
        ["CLM-1010-statement#0"] = "Driver statement: the other car entered on a red light and struck the front of the Volkswagen Passat. The policyholder provided the contact details of a witness.",
        ["CLM-1010-risk-summary#0"] = "Risk summary for CLM-1010: two anomalies were found — a significant benchmark excess of 89 percent and a mismatch between the photo and the list of works on the invoice. The claim requires human review before a decision. A payout is not recommended until the review is complete.",
        ["CLM-1010-coverage-check#0"] = "Coverage check: the road accident at the intersection falls under Auto Comprehensive coverage. No exclusion (intoxication, racing) was established. However the payout is suspended because of the invoice and photo anomalies.",
        ["CLM-1010-similar-signal#0"] = "Similar precedent: claim CLM-1006 also involved front bumper damage to a Toyota Camry from a collision together with a benchmark excess. The comparative analysis shows a recurring pattern of questionable invoices for bumper work.",
        ["CLM-1011-application#0"] = "Customer statement: road accident on 30.05.2026 in Salem. Hyundai Tucson, the rear bumper was damaged in a rear-end impact. The customer did not call the police and only signed a handwritten receipt with the other driver.",
        ["CLM-1011-invoice#0"] = "Repair invoice Salem: rear bumper replacement for the Hyundai Tucson 850 dollars, bodywork 400 dollars. Total amount 1250 dollars. The invoice was provided, but the police report is missing.",
        ["CLM-1011-missing-police#0"] = "The police report is missing. The customer stated that the police were not called. Only a handwritten receipt from the other driver was provided. Without an official police report the fact and circumstances of the accident cannot be confirmed.",
        ["CLM-1011-missing-police#1"] = "Policy documentation requirements: an official police report or an accident certificate is required for road accident indemnity. A handwritten receipt is not an official document and cannot replace the police report.",
        ["CLM-1011-statement#0"] = "Driver statement: the customer states that at the time of the accident they settled with the other driver without calling the police. The other driver signed a receipt accepting responsibility. The customer asks that the claim be considered without a police report.",
        ["CLM-1011-missing-docs-summary#0"] = "Document summary for CLM-1011: the mandatory police report is missing. The repair invoice is present. A request must be sent to the customer to obtain an official accident document (police report or form 6 certificate).",
        ["CLM-1011-risk-advisory#0"] = "Advisory note: claim CLM-1011 cannot be resolved without the police report. Until an official document is provided the payout is suspended. The claim requires further documentation by the customer.",
        ["CLM-1011-coverage-check#0"] = "Coverage check for CLM-1011: the rear-end impact on the Hyundai Tucson falls under Auto Comprehensive coverage provided official confirmation of the accident is supplied. Without a police report or certificate the insured event cannot be confirmed.",
    };

    /// <summary>ClauseId -> canonical English (Title, Text).</summary>
    public static readonly IReadOnlyDictionary<string, (string Title, string Text)> ClauseText =
        new Dictionary<string, (string, string)>(StringComparer.Ordinal)
    {
        ["CLA-AC-COVER-001"] = ("Road accident coverage", "The Auto Comprehensive policy covers losses resulting from a road traffic accident and collision of vehicles."),
        ["CLA-AC-COVER-002"] = ("Natural events and theft", "Damage from natural events, fire and theft of the vehicle is covered."),
        ["CLA-AC-EXCL-001"] = ("Exclusion: intoxication", "Losses caused while driving under the influence of alcohol or drugs are not covered."),
        ["CLA-AC-EXCL-002"] = ("Exclusion: racing", "Losses incurred while taking part in racing or driving off public roads are not covered."),
        ["CLA-AC-DED-001"] = ("Deductible", "A deductible of 500 US dollars applies to every insured event."),
        ["CLA-AC-LIM-001"] = ("Bodywork repair limit", "The bodywork repair limit is determined by the market value of comparable work in the region."),
        ["CLA-TP-COVER-001"] = ("Third-party liability coverage", "The Auto Third-Party policy covers losses caused to third parties in a road traffic accident for which the policyholder is at fault."),
        ["CLA-TP-LIM-001"] = ("Third-party liability limit", "The maximum indemnity for third-party property damage is 130,000 US dollars; for bodily injury 260,000 US dollars per event."),
    };

    /// <summary>QuestionId -> canonical English (Text, ExpectedAnswerKeywordsCsv).</summary>
    public static readonly IReadOnlyDictionary<string, (string Text, string Keywords)> QuestionText =
        new Dictionary<string, (string, string)>(StringComparer.Ordinal)
    {
        ["Q-COVER-1006-1"] = ("Does the policy cover road accident damage and what is the deductible?", "cover,deductible,500"),
        ["Q-MISS-1006-1"] = ("Which documents are missing in this claim — is the rear bumper photo absent?", "photo,rear,missing"),
        ["Q-RISK-1006-1"] = ("Why does this claim carry elevated risk — does the repair estimate exceed the benchmark?", "exceeds,benchmark"),
        ["Q-SUMM-1006-1"] = ("Prepare an evidence summary for the decision — police report, accident, repair invoice.", "accident,repair"),
        ["Q-COVER-1007-1"] = ("What is known about the damage — side collision, door, mirror in this claim?", "side,door"),
        ["Q-MISS-1007-1"] = ("Which documents are missing — is the repair invoice absent?", "invoice,missing"),
        ["Q-SUMM-1008-1"] = ("Prepare an evidence summary — complete claim, low risk, payout recommendation.", "Low risk,anomalies,payout"),
        ["Q-COVER-1008-1"] = ("Is the insured event covered by the policy? Exclusion check, documents complete.", "covered,exclusion,complete"),
        ["Q-RISK-1008-1"] = ("What is the risk level of the claim — no deviation found, benchmark normal?", "benchmark,deviation"),
        ["Q-COVER-1009-1"] = ("Is this claim covered by the policy? Alcohol intoxication exclusion check.", "exclusion,intoxication,alcohol"),
        ["Q-DENY-1009-1"] = ("Prepare a denial summary — intoxication, denial, notice to the customer.", "denial,intoxication,payout"),
        ["Q-RISK-1009-1"] = ("What is the basis for denial — medical report, alcohol, police report?", "Medical report,alcohol,intoxication"),
        ["Q-MISS-1009-1"] = ("Which documents are present in the claim — repair invoice, police report?", "invoice,repair,amount"),
        ["Q-RISK-1010-1"] = ("Why does the claim carry elevated risk — benchmark excess and photo/invoice mismatch?", "excess,benchmark,mismatch"),
        ["Q-RISK-1010-2"] = ("What decision is recommended for a risky claim — human review, payout suspension?", "anomalies,requires,review"),
        ["Q-COVER-1010-1"] = ("Does the intersection road accident fall under Auto Comprehensive coverage with no exclusion established?", "coverage,exclusion,intersection"),
        ["Q-SUMM-1010-1"] = ("Evidence summary for the claim — invoice, repair, bumper, bonnet, police report Greenville?", "collision,bumper,repair"),
        ["Q-MISS-1011-1"] = ("Which documents are missing — police report absent, handwritten receipt does not replace it?", "police report,missing,receipt"),
        ["Q-MISS-1011-2"] = ("Which documents does the policy require for accident indemnity — official report or certificate?", "police report,certificate,official"),
        ["Q-RISK-1011-1"] = ("What is the claim risk without a police report — payout suspended, documentation?", "suspended,documentation,police report"),
        ["Q-SUMM-1011-1"] = ("Prepare the list of missing documents for the decision — request police report, form 6?", "police report,form 6,request"),
    };
}
