using InsuranceAIPlatform.Services.AiAnalysis.Persistence;
using InsuranceAIPlatform.Services.Approval.Persistence;
using InsuranceAIPlatform.Services.Documents.Persistence;
using Microsoft.EntityFrameworkCore;

namespace InsuranceAIPlatform.DbMigrator;

/// <summary>
/// Lease 8 historical-data backfill — a THIRD, separately recorded version. The
/// v1 (<c>english-only-v1</c>) and v2 (<c>english-only-closure-v2</c>) contracts are
/// left exactly as recorded; nothing about them is rewritten.
///
/// Scope: the six historical synthetic/demo columns reported by Lease 7 whose values
/// are free-form prose generated by past runs against the pre-translation corpus.
/// There is no fixture-evidenced 1:1 translation for them, so rather than guess one,
/// the owner authorized explicit NEUTRAL replacement sentences that state plainly that
/// the row is a migrated historical record.
///
/// Rules:
///   - A row is touched ONLY if its current value contains Cyrillic.
///   - Only these six columns are eligible. Nothing else is inspected or written.
///   - UPDATE only. No delete, truncate or drop. Ids, foreign keys, timestamps, claim
///     scoping and the existence of every audit row are preserved untouched.
///   - Idempotent by construction: the replacements contain no Cyrillic, so a second
///     run finds nothing eligible and performs 0 updates.
/// </summary>
public static class EnglishOnlyHistoricalBackfill
{
    public const string Version = "english-only-historical-v3";

    // Owner-authorized neutral replacements (verbatim from the Lease 8 request).
    private const string RagAnswer =
        "Historical advisory analysis migrated to English-only mode. Re-run the analysis to refresh the detailed answer.";
    private const string RagQuery =
        "Historical query migrated to English-only mode. Re-run the analysis to refresh the exact query.";
    private const string DocContent =
        "Historical synthetic test document content migrated to English-only mode.";
    private const string MissingDocReason =
        "Required to complete the claim assessment.";
    private const string RunSummary =
        "Historical advisory AI analysis migrated to English-only mode. Re-run the analysis for current details.";
    private const string ApprovalNote =
        "Historical synthetic approval note migrated to English-only mode.";

    private static bool HasCyrillic(string? s) =>
        !string.IsNullOrEmpty(s) && s.Any(c => c >= 'Ѐ' && c <= 'ӿ');

    private const string EnsureHistorySql = """
        IF OBJECT_ID(N'[dbo].[DataBackfillHistory]', N'U') IS NULL
        CREATE TABLE [dbo].[DataBackfillHistory](
            [Version]       NVARCHAR(100)     NOT NULL PRIMARY KEY,
            [AppliedAtUtc]  DATETIMEOFFSET    NOT NULL,
            [Updated]       INT               NOT NULL,
            [Skipped]       INT               NOT NULL,
            [RunCount]      INT               NOT NULL
        );
        """;

    public static async Task<bool> WasAppliedAsync(DbContext db, CancellationToken ct)
    {
        await db.Database.ExecuteSqlRawAsync(EnsureHistorySql, ct);
        var rows = await db.Database
            .SqlQueryRaw<int>("SELECT COUNT(*) AS Value FROM [dbo].[DataBackfillHistory] WHERE [Version] = {0}", Version)
            .ToListAsync(ct);
        return rows.FirstOrDefault() > 0;
    }

    private static async Task RecordAsync(DbContext db, BackfillReport r, CancellationToken ct)
    {
        const string sql = """
            IF EXISTS (SELECT 1 FROM [dbo].[DataBackfillHistory] WHERE [Version] = {0})
                UPDATE [dbo].[DataBackfillHistory]
                   SET [AppliedAtUtc] = SYSDATETIMEOFFSET(),
                       [Updated] = [Updated] + {1}, [Skipped] = {2}, [RunCount] = [RunCount] + 1
                 WHERE [Version] = {0};
            ELSE
                INSERT INTO [dbo].[DataBackfillHistory]([Version],[AppliedAtUtc],[Updated],[Skipped],[RunCount])
                VALUES ({0}, SYSDATETIMEOFFSET(), {1}, {2}, 1);
            """;
        await db.Database.ExecuteSqlRawAsync(sql, new object[] { Version, r.Updated, r.Skipped }, ct);
    }

    public static async Task<BackfillReport> RunAsync(
        AiAnalysisDbContext ai, DocumentsDbContext documents, ApprovalDbContext approval,
        Microsoft.EntityFrameworkCore.DbContext checkpointDb, CancellationToken ct)
    {
        var r = new BackfillReport { Version = Version };

        // --- ai_analysis.RagAuditTraces.AnswerText / .QueryText -------------
        foreach (var t in await ai.RagAuditTraces.ToListAsync(ct))
        {
            if (HasCyrillic(t.AnswerText)) { t.AnswerText = RagAnswer; r.Updated++; } else r.AlreadyEnglish++;
            if (HasCyrillic(t.QueryText))  { t.QueryText  = RagQuery;  r.Updated++; } else r.AlreadyEnglish++;
        }

        // --- ai_analysis.AiAnalysisRuns.SummaryText -------------------------
        foreach (var run in await ai.AiAnalysisRuns.ToListAsync(ct))
        {
            if (HasCyrillic(run.SummaryText)) { run.SummaryText = RunSummary; r.Updated++; } else r.AlreadyEnglish++;
        }
        await ai.SaveChangesAsync(ct);

        // --- documents.ClaimDocuments.Content -------------------------------
        foreach (var d in await documents.ClaimDocuments.ToListAsync(ct))
        {
            if (HasCyrillic(d.Content)) { d.Content = DocContent; r.Updated++; } else r.AlreadyEnglish++;
        }

        // --- documents.MissingDocumentRequests.Reason -----------------------
        foreach (var m in await documents.MissingDocumentRequests.ToListAsync(ct))
        {
            if (HasCyrillic(m.Reason)) { m.Reason = MissingDocReason; r.Updated++; } else r.AlreadyEnglish++;
        }
        await documents.SaveChangesAsync(ct);

        // --- approval.ApprovalDrafts.Notes ----------------------------------
        foreach (var a in await approval.ApprovalDrafts.ToListAsync(ct))
        {
            if (HasCyrillic(a.Notes)) { a.Notes = ApprovalNote; r.Updated++; } else r.AlreadyEnglish++;
        }
        await approval.SaveChangesAsync(ct);

        await RecordAsync(checkpointDb, r, ct);
        return r;
    }
}
